name: A Bon Blog
#GitHub Project Pages Settings
url: "http://ninapetrop.github.io/a-bon-blog/"
baseurl: "/a-bon-blog/"
url-pretty: "ninapetrop.github.io/a-bon-blog/"
markdown: kramdown
highlighter: rouge
exclude: ["node_modules", "gulpfile.js", "package.json"]
instagram: http://example.net
twitter: http://example.net
facebook: http://example.net
youtube: http://example.net

collections:
  category:
    output: true

defaults:
  -
    scope:
      path: ""
      type: category
    values:
      layout: "category"
